server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: clientserver
    password: clientserverpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          auth-server:
            provider: spring
            client-id: client-server-back
            client-secret: secret
            client-authentication-method: client_credentials
            scope: users:read
            client-name: auth-server
        provider:
          spring:
            issuer-uri: http://localhost:9000
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          # jwk-set-uri: http://localhost:9000/oauth2/jwks
